[package]
name = "rusttest"
version = "0.1.0"
authors = ["Daniel Beecham <daniel@lunix.se>"]

[profile.release]
opt-level = 'z'
panic = "abort"
lto = false
codegen-units = 1

[profile.dev]
panic = "abort"

[dependencies]
libc = { version = "0.2.0", default-features = false }
